# Spring properties
spring:
  # Dev is active by default. This value can be overwritten by java arg param 
  profiles:
    active: heroku
  application:
    name: registroactividades-api
  messages:
    basename: bundles/languageBundle
    
logging:
  level.root: INFO
  file: registro-actividades.log